language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake g++ libgtkmm-2.4-dev libglademm-2.4-dev libgtksourceview2.0-dev libboost1.48-dev libboost-serialization1.48-dev libboost-date-time1.48-dev libboost-filesystem1.48-dev libboost-test1.48-dev libboost-regex1.48-dev libboost-program-options1.48-dev libboost-thread1.48-dev libboost-chrono1.48-dev  libasio-dev libopenmpi-dev openmpi-bin libarchive-dev 

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make

notifications:
  recipients:
    - gauthier.quesnel@toulouse.inra.fr
  email:
    on_success: change
    on_failure: always
  irc:
    channels:
      - "chat.freenode.net#vle"
    template:
      - "%{repository} (%{commit}) : %{message} %{foo} "
      - "Build details: %{build_url}"
